# Generated by Django 6.0.2 on 2026-02-11 15:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Facility',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('code', models.CharField(max_length=50, unique=True)),
                ('location', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Refill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unique_id', models.CharField(max_length=100)),
                ('last_pickup_date', models.DateField()),
                ('sex', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=10)),
                ('months_of_refill_days', models.IntegerField(choices=[(30, '30 Days'), (60, '60 Days'), (90, '90 Days'), (180, '180 Days')])),
                ('current_regimen', models.CharField(max_length=255)),
                ('case_manager', models.CharField(max_length=255)),
                ('remark', models.TextField(blank=True, null=True)),
                ('next_appointment', models.DateField(blank=True, null=True)),
                ('expected_iit_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('facility', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='refills', to='refills.facility')),
            ],
            options={
                'ordering': ['-last_pickup_date'],
                'indexes': [models.Index(fields=['facility'], name='refills_ref_facilit_26db0f_idx'), models.Index(fields=['next_appointment'], name='refills_ref_next_ap_a7555c_idx'), models.Index(fields=['last_pickup_date'], name='refills_ref_last_pi_62dc4b_idx')],
                'unique_together': {('facility', 'unique_id')},
            },
        ),
    ]
