# Generated by Django 6.0.2 on 2026-02-18 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('refills', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='refill',
            name='current_art_status',
            field=models.CharField(choices=[('Active', 'Active'), ('Active Restart', 'Active Restart'), ('Inactive', 'Inactive')], default='Active', max_length=20),
        ),
        migrations.AddField(
            model_name='refill',
            name='missed_appointment',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='refill',
            name='months_of_refill_days',
            field=models.DecimalField(decimal_places=2, max_digits=4),
        ),
    ]
