# Generated by Django 6.0.2 on 2026-02-12 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('refills', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='refill',
            name='current_art_status',
            field=models.CharField(choices=[('Active', 'Active'), ('Active Restart', 'Active Restart'), ('Inactive', 'Inactive')], default='Active', max_length=20),
        ),
    ]
