# Generated by Django 6.0.2 on 2026-02-19 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('refills', '0002_refill_current_art_status_refill_missed_appointment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='refill',
            name='art_start_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='refill',
            name='viral_load_sample_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
