# Generated by Django 6.0.2 on 2026-02-12 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('refills', '0002_refill_current_art_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='refill',
            name='missed_appointment',
            field=models.BooleanField(default=False),
        ),
    ]
