# Generated by Django 6.0.2 on 2026-02-19 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('refills', '0003_refill_art_start_date_refill_viral_load_sample_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='refill',
            name='vl_suppressed',
            field=models.BooleanField(default=False),
        ),
    ]
