# Generated by Django 6.0.2 on 2026-02-19 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('refills', '0004_refill_vl_suppressed'),
    ]

    operations = [
        migrations.RenameField(
            model_name='refill',
            old_name='viral_load_sample_date',
            new_name='vl_sample_collection_date',
        ),
        migrations.RemoveField(
            model_name='refill',
            name='vl_suppressed',
        ),
        migrations.AddField(
            model_name='refill',
            name='vl_result',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='refill',
            name='last_pickup_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
